name: On Push build
on:
  push:
    branches:
      - master
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2 # If you're using actions/checkout@v2 you must set persist-credentials to false in most cases for the deployment to work correctly.
      with:
        persist-credentials: false
    - name: Install and Build
      run: |
        npm install
        npm run-script build

    - name: Write to file 1
      run: | 
        echo -e "\n No CRITICAL or HIGH Vulnerabilities found on builds" >> emailresults.txt
      shell: bash

    - name: Write to file 2
      run: | 
        echo -e "\n CRITICAL or HIGH Vulnerabilities found on builds" >> emailresults.txt
      shell: bash

    - name: Write to file 2
      run: | 
        echo -e "\n NO CRITICAL or HIGH Vulnerabilities found on builds" >> emailresults.txt
      shell: bash

    - name: Set the value
 #     id: step_one
      run: |
        echo 'RESULTS<<EOF' >> $GITHUB_ENV
        cat emailresults.txt >> $GITHUB_ENV
        echo 'EOF' >> $GITHUB_ENV


    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@v4.2.5
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        BRANCH: gh-pages
        FOLDER: build
    - name: Send mail
      uses: dawidd6/action-send-mail@v3
      with:
        # Required mail server address:
        server_address: smtp.gmail.com
        # Required mail server port:
        server_port: 465
        # Optional (recommended): mail server username:
        username: ${{secrets.EMAIL_USERNAME}}
        # Optional (recommended) mail server password:
        password: ${{secrets.EMAIL_PASSWORD}}
        # Required mail subject:
        subject: Github Actions job result
        # Required recipients' addresses:
        to: fitim.osmani@scalable.capital
        # Required sender full name (address can be skipped):
        from: githubnotificationstest@gmail.com
        # Optional whether this connection use TLS (default is true if server_port is 465)
        secure: true
        # Optional plain body:
        body: Build job of ${{github.repository}} completed successfully!  Find te results below  ${{ env.RESULTS }} 
             

